# name: Test install Ubuntu
# 
# on:
#   push:
#     branches: [ master ]
#   	
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - run: sudo apt install shellcheck
#     - run: shellcheck backuppc-manage.sh
#     - run: sudo backuppc-manage.sh

# name: Test install Ubuntu

name: Test install Ubuntu
on: push

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:16.04', 'ubuntu:18.04']
    steps:
    - run: cat /etc/debian_version
#   test-install:
#   	name: Install on ${{matrix.container }}
#     runs-on: ubuntu-latest
#     container: ${{ matrix.container }}
#     strategy:
#       matrix:
#         container: ['ubuntu:20.04', 'ubuntu:18.04']
#     steps:
#     - uses: actions/checkout@v1
#       with:
#         fetch-depth: 1
#     - name: Version
#       run: cat /etc/debian_version || cat /etc/centos-release
#     - name: Install
#       run: sudo bash ./backuppc-manage.sh --install
