# name: Test install Ubuntu
# 
# on:
#   push:
#     branches: [ master ]
#   	
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#     - run: sudo apt install shellcheck
#     - run: shellcheck backuppc-manage.sh
#     - run: sudo backuppc-manage.sh

# name: Test install Ubuntu

name: Test install Ubuntu
on: push

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  translations:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install xmllint
      run: apt-get install libxml2-utils
#   install:
#     name: Install
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
# 	- name: Hooray
# 	  run: "sudo apt-get install libxml2-utils"

# 	- name: Run install
#       uses: jcblw/bash@master
# 	  args: [ "./backuppc-manage.sh"]
#     - name: Run install
#       run: .backuppc-manage.sh
