name: Test Install
on: push

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  install-debian-like:
    name: Install on Linux Distribution
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:20.04', 'debian:buster', 'centos:8', 'fedora:34']
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Version
        run: cat /etc/debian_version || cat /etc/redhat-release
      - name: Test Install
        run: ./test.sh
