name: Test install Ubuntu

on:
  push:
    branches: [ master ]
  	
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: sudo apt install shellcheck
    - run: shellcheck backuppc-manage.sh
    - run: sudo backuppc-manage.sh
