name: Test install Ubuntu
on: push

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
  build:
    name: Build on ${{matrix.container }}
    runs-on: ubuntu-latest
    container: ${{ matrix.container }}
    strategy:
      matrix:
        container: ['ubuntu:20.04', 'ubuntu:18.04']
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Version
      run: cat /etc/debian_version || cat /etc/centos-release
    - name: install Sudo
      run: apt update && export DEBIAN_FRONTEND=noninteractive && export TZ=Europe/Berlin && apt -y install sudo tzdata
    - name: Install
      run: ./backuppc-manage.sh --install --confirm --backuppc-version 4.4.0 --rsync-bpc-version 3.1.3.0